stages:
  - build
  - test
  - docker

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/test-results

docker:
  stage: docker
  script:
    - docker build -t ias3_be .

