stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/test-results

deploy:
  stage: deploy
  script:
    - |
      if [[ "$CI_BUILD_BEFORE_SHA" == "$CI_BUILD_REF" && "$CI_COMMIT_BRANCH" == "main" ]]; then
        docker build -t ias3_be .
        docker run -d -p 9000:8080 --name ias_container_be ias3_be
      else
        echo "Skipping deployment as previous stages failed or pipeline was not triggered by the main branch."
      fi
  dependencies:
    - build
    - test


