stages:
  - build
  - test
  - sonarqube-check
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/test-results

sonarqube-check:
  stage: sonarqube-check
  image: gradle:8.2.0-jdk17-jammy
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew sonar
  allow_failure: false
  only:
    - merge_requests
    - master
    - main
    - develop

deploy:
  stage: deploy
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        # Stop and remove existing container if it exists
        if [ "$(docker ps -q -f name=ias3_container_be)" ]; then
          docker stop ias3_container_be || true
          sleep 5
          docker rm ias3_container_be || true
          sleep 5
        fi
        # Build the new image
        docker build -t ias3_be .
        # Run the new container
        docker run -d -p 8000:8080 --name ias3_container_be ias3_be
      else
        echo "Skipping deployment as the pipeline was not triggered by the main branch."
      fi
  only:
    - main






