plugins {
    id 'java'
    id 'org.springframework.boot' version '3.1.0'
    id 'io.spring.dependency-management' version '1.1.0'
    id("org.sonarqube") version "4.4.1.3373"
    id "jacoco"
}

group = 'Marketplace'
version = '1.0-SNAPSHOT'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
/*    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'*/
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'
    implementation 'mysql:mysql-connector-java:8.0.33'

/*    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'*/

    compileOnly 'org.projectlombok:lombok'

    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.springframework.cloud:spring-cloud-starter-bootstrap:4.0.4'
    testImplementation 'org.testcontainers:testcontainers:1.16.3'
    testImplementation 'com.playtika.testcontainers:embedded-mysql:3.0.0-RC9'
/*
    testImplementation 'org.springframework.security:spring-security-test'
*/
}

test {
    useJUnitPlatform()
}

sonar {
    properties {
        property "sonar.projectKey", "***REMOVED***"
        property "sonar.projectName", "My individual assignment semester 3_BE"
        property "sonar.qualityGate.wait", true
        property "sonar.gradle.skipCompile", true
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"

    }
}

jacocoTestReport{
    dependsOn test
    reports{
        xml.required = true
        html.required = false
    }
}
